
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cryloop
 */
public class kasa extends javax.swing.JFrame {
    DefaultTableModel model;
    Operations op = new Operations();
    /**
     * Creates new form kasa
     */
    public kasa() {
        initComponents();
        model = (DefaultTableModel) sepet_table.getModel();
        sepetView();


    }
    
    ArrayList<String>kullaniciSira=new ArrayList<String>();
    ArrayList<String>kullanici=new ArrayList<String>();
    
    Connection con = null;
    Statement sta = null;
    PreparedStatement psta = null;
    ResultSet rs = null;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sepet_table = new javax.swing.JTable();
        tf_kullaniciAra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_kitapAd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_kitapFiyat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_kitapAdet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_kitapToplam = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_kitapAnaToplam = new javax.swing.JTextField();

        setTitle("Kasa");
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));
        setResizable(false);

        jLabel1.setText("Kullanıcı Adı: ");

        sepet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Kullanıcı", "Kitap Adı", "Yazar", "Tip", "Yayınevi", "Fiyat", "Stok", "Adet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sepet_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sepet_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sepet_table);

        tf_kullaniciAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_kullaniciAraKeyReleased(evt);
            }
        });

        jLabel2.setText("Kitap Adı:");

        tf_kitapAd.setEnabled(false);

        jLabel3.setText("Fiyat:");

        tf_kitapFiyat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_kitapFiyat.setEnabled(false);

        jLabel4.setText("Adet:");

        tf_kitapAdet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kitapAdetActionPerformed(evt);
            }
        });

        jLabel5.setText("Ara Toplam:");

        tf_kitapToplam.setEnabled(false);

        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        jLabel6.setText("Ana Toplam:");

        tf_kitapAnaToplam.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_kitapAdet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_kitapFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_kullaniciAra, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tf_kitapAd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_kitapToplam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(tf_kitapAnaToplam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_kullaniciAra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_kitapAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_kitapToplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ekle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btn_Sil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_kitapFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_kitapAnaToplam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_kitapAdet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sepet_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sepet_tableMouseClicked
        int selectedrow = sepet_table.getSelectedRow();
        tf_kitapAd.setText(model.getValueAt(selectedrow, 3).toString());
        tf_kitapFiyat.setText(model.getValueAt(selectedrow, 6).toString());
        tf_kitapAdet.setText(model.getValueAt(selectedrow, 8).toString());
        
    }//GEN-LAST:event_sepet_tableMouseClicked

    public void filter(String query)
    {
        TableRowSorter<DefaultTableModel> trs =  new TableRowSorter<DefaultTableModel>(model);
        sepet_table.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(query));
    }
    private void tf_kullaniciAraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_kullaniciAraKeyReleased
        String query = tf_kullaniciAra.getText();
        filter(query);
    }//GEN-LAST:event_tf_kullaniciAraKeyReleased
    public int anaToplam=0;
    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        String fiyat = tf_kitapFiyat.getText();
        String adet = tf_kitapAdet.getText();
        int fiyatY=Integer.parseInt(fiyat);
        int adetY=Integer.parseInt(adet);
        
        int toplam;
        toplam=adetY*fiyatY;
        
        anaToplam= anaToplam+toplam;
        
        String toplamY=Integer.toString(toplam);
        tf_kitapToplam.setText(toplamY);
        
        String anaToplamY=Integer.toString(anaToplam);
        tf_kitapAnaToplam.setText(anaToplamY);
        
        int selectedrow = sepet_table.getSelectedRow();
        if(selectedrow==-1)
        {
            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "Seçim Yapmadınız");
              
            }else{
                JOptionPane.showMessageDialog(null, "Seçim Yapmadınız");
            }
        }else{
            int id = (int)model.getValueAt(selectedrow, 0);
            String kitapAd=(String)model.getValueAt(selectedrow, 2);
            int stok = (int) model.getValueAt(selectedrow, 8);
            String kitapY=tf_kitapAdet.getText();
            int kitapYA=Integer.parseInt(kitapY);
            op.SepetUpdate(kitapAd,kitapYA);
            op.sepetBookDelete(id);
            sepetView();
        }
        
        
        
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        int selectedrow = sepet_table.getSelectedRow();
        if(selectedrow==-1)
        {
            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "Seçim Yapmadınız");
              
            }else{
                JOptionPane.showMessageDialog(null, "Seçim Yapmadınız");
            }
        }else{
            int id = (int)model.getValueAt(selectedrow, 0);
            op.sepetBookDelete(id);
            sepetView();
            tf_kitapAd.setText(null);
            tf_kitapToplam.setText(null);
            tf_kitapAdet.setText(null);
           // tf_kitapAnaToplam.setText(null);
            tf_kitapFiyat.setText(null);
        }
    }//GEN-LAST:event_btn_SilActionPerformed

    private void tf_kitapAdetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kitapAdetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kitapAdetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasa().setVisible(true);
            }
        });
    }
    
    
    public void sepetView(){
        model.setRowCount(0);
        ArrayList<Sepet> sepets= new ArrayList<Sepet>();
        sepets=op.SepetListe();
        
        if(sepets!=null)
        {
        
            for(Sepet sepetx : sepets){
                Object[] add= {
                    sepetx.getId(),sepetx.getKullanici_adi(),sepetx.getKitap_ad(),sepetx.getKitap_yazar(),sepetx.getKitap_tip(),sepetx.getKitap_yayinevi(),sepetx.getFiyat(),sepetx.getStok(),sepetx.getAdet()
                };
                model.addRow(add);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sil;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sepet_table;
    private javax.swing.JTextField tf_kitapAd;
    private javax.swing.JTextField tf_kitapAdet;
    private javax.swing.JTextField tf_kitapAnaToplam;
    private javax.swing.JTextField tf_kitapFiyat;
    private javax.swing.JTextField tf_kitapToplam;
    private javax.swing.JTextField tf_kullaniciAra;
    // End of variables declaration//GEN-END:variables
}
